booksapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from gestion.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion/',include('gestion.urls',)),
    path('',RedirectView.as_view(url='/gestion/',permanent = True)),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls. static import static
from . import views


urlpatterns = [
    path('',views.index, name='index'),
    path('books/',views.BookListView.as_view(),name='books'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name ='book-detail'),
    path('editbook/<int:pk>', views.EditBook.as_view(), name = 'edit-book'),
    path('booksinstance/', views.AddBookInstance.as_view(), name ='bookinstance'),
    path('authors/', views.AuthorListView.as_view(), name = 'authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name = 'author-detail'),
    path('mybooks/',views.LoanedBooksByUserListView.as_view(), name = 'my-borrowed'),
    path('myreserved/',views.ReservedBooksByUserListView.as_view(), name = 'my-reserved'),
    path('allborrowed/',views.AllLoanedBooks.as_view(), name = 'all-borrowed'),
    path('addbook/',views.AddBook.as_view(), name = 'add-book'),
    path('addauthor/',views.AddAuthor.as_view(), name = 'add-author'),
    path('genre/',views.GenreView.as_view(), name = 'genre'),
    path('addgenre/',views.AddGenre.as_view(), name = 'add-genre'),
    path('language/',views.LanguageView.as_view(), name = 'language'),
    path('addlanguage/',views.AddLanguage.as_view(), name = 'add-language'),
    path('loanbook/<slug:pk>',views.ToLoanBook.as_view(), name ='loan-book'),
    path('deletebook/<slug:pk>/',views.DeleteBookInstance.as_view(), name = 'delete-book'),
    path('reservebook/<slug:pk>/',views.ReserveBook.as_view(), name = 'reserve-book'),
    path('members/',views.MemberListView.as_view(), name = 'members'),
    path('member/<int:pk>',views.MemberDetailView.as_view(), name = 'member-detail'),
    path('addmember/',views.AddMember.as_view(), name = 'add-member'),
    path('deletemember/<int:pk>/',views.DeleteMember.as_view(), name = 'delete-member'),
    path('editmember/<int:pk>/',views.EditMember.as_view(), name = 'edit-member'),
    path('counter/<int:pk>/',views.CounterBook.as_view(), name = 'counter-book'),
    path('mostcounted/',views.MostCounted.as_view(), name = 'most-counted'),
    path('addreview/<int:book_pk>/',views.AddReview.as_view(), name = 'add-review'),
    path('listreview/',views.ListReview.as_view(), name = 'list-reviews'),
    path('bementor/',views.AddMentor.as_view(), name = 'be-mentor'),
    path('mentorlist/',views.MentorList.as_view(), name = 'mentor-list'),
    path('deletementor/<slug:pk>',views.DeleteMentor.as_view(), name = 'delete-mentor'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid # Requerida para las instancias de libros únicos
import numpy as np

class Genre(models.Model):
    name = models.CharField(verbose_name = 'Genero', max_length=200,
        help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)")
    
    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(verbose_name = 'Lenguaje', max_length=200,
        help_text="Ingrese lenguaje de libro")
    
    def __str__(self):
        return self.name

class Member(models.Model):
    first_name = models.CharField(max_length = 100, verbose_name = 'Nombre')
    last_name = models.CharField(max_length = 100, verbose_name = 'Apellido')
    email = models.EmailField(blank = True, null = True)
    phone_num = models.CharField(max_length = 15, verbose_name = 'No Telefono')
    memberID = models.ForeignKey(User, on_delete=models.SET_NULL, null = True, blank = True, verbose_name="ID de") 

    def __str__(self):
        return '%s %s' % (self.first_name,self.last_name)


class Book(models.Model):
    """
    Modelo que representa un libro (pero no un Ejemplar específico).
    """
    title = models.CharField(verbose_name = 'Titulo', max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, verbose_name = 'Autor')
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    # 'Author' es un string, en vez de un objeto, porque la clase Author aún no ha sido declarada.
    summary = models.TextField(max_length=1000, 
        help_text="Ingrese una breve descripción del libro", verbose_name = 'Resumen')  
    isbn = models.CharField('ISBN',max_length=13,
        help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, 
        help_text="Seleccione los generos de este libro", verbose_name = 'Genero')
    # ManyToManyField, porque un género puede contener muchos libros y un libro puede cubrir varios géneros.
    # La clase Genre ya ha sido definida, entonces podemos especificar el objeto arriba.
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, verbose_name = 'Lenguaje')
    image = models.ImageField(upload_to = 'gestion', null = True, blank = True, verbose_name = 'Imagen')
    counter = models.IntegerField(blank = True, null = True, default = 0)
    
    def __str__(self):

        return self.title
    
    def get_absolute_url(self):

        return reverse('book-detail', args=[str(self.id)]) #Devuelve la URL a una instancia particular de Book
    
    def display_genre(self):
  
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ]) #Crea string para el genero (para Admin)
    
    display_genre.short_description = 'Genre'

    def average_rating(self):       #funcion para obtener el promedio de ratings
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(list(all_ratings),dtype='int8')


class BookInstance(models.Model):
    """
    Modelo que representa una copia específica de un libro (una biblioteca puede tener varios ejemplares de un libro)
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, verbose_name = 'Libro') 
    imprint = models.CharField(max_length=200, verbose_name = 'Editorial')
    due_back = models.DateField(null=True, blank=True, verbose_name = 'Fecha devolución', help_text = 'Si tiene fecha de devolucion el estado no puede ser Disponible')
    loan_date = models.DateField(null=True, blank=True,)

    LOAN_STATUS = (
        ('o', 'En prestamo'),
        ('a', 'Disponible'),
        ('r', 'Reservado'),
    )

    status = models.CharField(max_length = 1, choices = LOAN_STATUS, blank = True, default='a', verbose_name = 'Estado', help_text = 'No puede estar diponible y con fecha de devolucion')

    MAIN_CLASIFICATION = (
        ('a','Academico'),
        ('l','Literatura'),
        ('n','No ficción'),
    )

    main_class = models.CharField(max_length = 1, choices = MAIN_CLASIFICATION, blank = True, verbose_name = 'Estantería',  help_text = '(Academico, Literatura, No ficción)')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null = True, blank = True, verbose_name="Prestatario")
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)        

    def __str__(self):

        return '%s (%s)' % (self.id,self.book.title)


class Author(models.Model):

    first_name = models.CharField(max_length=100, verbose_name = 'Nombre')
    last_name = models.CharField(max_length=100, verbose_name = 'Apellido')
    
    class Meta:
        ordering = ['last_name']
    
    def get_absolute_url(self):
 
        return reverse('author-detail', args=[str(self.id)]) #Retorna la url para acceder a una instancia particular de un autor.
   
    def __str__(self):

        return '%s, %s' % (self.last_name, self.first_name)


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    book = models.ForeignKey(Book, null = True, on_delete = models.DO_NOTHING, verbose_name = 'Libro')
    pub_date = models.DateTimeField(auto_now=True,verbose_name = 'Fecha de publicacion')
    user_name = models.ForeignKey(User, on_delete=models.SET_NULL, null = True, blank = True)
    comment = models.TextField(verbose_name = 'Reseña')
    rating = models.IntegerField(choices=RATING_CHOICES,verbose_name = 'Clasificación')
    class Meta:
        ordering = ['-pub_date']

    def get_absolute_url(self):

        return reverse('review-detail', args=[str(self.id)])

class Mentor(models.Model):
    mentor = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = 'Referente')
    book = models.ForeignKey(Book, on_delete = models.CASCADE, verbose_name = 'Libro')
    contact_email = models.EmailField(verbose_name = 'E-mail de contacto')

gestion/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime 
from django import forms
from .models import Book, Author, Language, Genre, BookInstance


class AddBookInstanceForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book','imprint','main_class',]


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title','author','summary','isbn','genre','language','image',]


class AddAuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name','last_name',]

class AddLanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = ['name',]

class AddGenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name',]

gestion/templates/gestion/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1> {{ author.first_name }} {{ author.last_name }}</h1>

<div style="margin-left:20px;margin-top:20px">

{% if author.book_set.all %}
  <h4>Sus libros</h4>

  <dl>
    {% for book in author.book_set.all %}
      <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
      <dd>{{book.summary}}</dd>
    {% endfor %}
  </dl>
{% else %}
  <h4>No tenemos libros de este autor</h4>

{% endif %}
</div>
{% endblock %}

gestion/templates/gestion/author_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Ingreso de nuevo autor</h1>
    <form  role="form"  enctype="multipart/form-data" action="" method="POST" id="upload-image-form">   
        {% csrf_token %}   
        {{ form.as_p }}       
        
        <button type="submit" formmethod="post">Enviar</button>
    </form>
{% endblock content %} 

gestion/templates/gestion/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Listado de autores</h1>

    {% if object_list %}
    <ul>

      {% for author in object_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{author.first_name}}</a> <!--href indica una url al detalle del libro en particular-->
      </li>
      {% endfor %}

      <br><a href="{% url 'add-author' %}">Agregar autor</a>
    </ul>
    {% else %}
      <p>No hay autores ingresados.</p>
    {% endif %}       
{% endblock %}

gestion/templates/gestion/book_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Ingreso de nuevo libro</h1>
    <form  role="form"  enctype="multipart/form-data" action="" method="POST" id="upload-image-form">   
        {% csrf_token %}   
        {{ form.as_p }}       
        
        <button type="submit" formmethod="post">Enviar</button>
    </form>
{% endblock content %} 

gestion/templates/gestion/bookinstance_add_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Ingreso de nuevo libro</h1>
    <form  role="form"  enctype="multipart/form-data" action="" method="POST" id="upload-image-form">   
        {% csrf_token %}   
        {{ form.as_p }}       
        
        <button type="submit" formmethod="post">Enviar</button>
    </form>
{% endblock content %} 

gestion/templates/gestion/bookinstance_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
    <h1> {{ object.book }} de {{ object.book.author.first_name }} {{ object.book.author.last_name }}</h1>

{% if object.book.image %}
    <img src="{{ object.book.image.url }}" alt="{{ book.title }} "  style="width: 115px;height: 175px;">
{% endif %}

    <form action="" method="post">{% csrf_token %}
        <br><h4>Por favor, confirme borrar la copia de la editorial {{ object.imprint }} </h4><br>
        <input type="submit" value="BORRAR" />
    </form>

{% endblock %}

gestion/templates/gestion/bookinstance_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Libros en prestamos</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> (Prestado a <u><b>{{ bookinst.borrower }}</u></b>, devuelve {{ bookinst.due_back }})
        <a href="{% url 'loan-book' bookinst.id %}">[Modificar prestamo]</a>    
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No tienes libros en prestamo</p>
    {% endif %}       
{% endblock %}

gestion/templates/gestion/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Libros que tienes en prestamo</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No tienes libros en prestamo</p>
    {% endif %}       
{% endblock %}

gestion/templates/gestion/counter_book.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Confirme que desea el libro</h1>
    <form  role="form"  enctype="multipart/form-data" action="" method="POST" id="upload-image-form">   
        {% csrf_token %}        
        
        <button type="submit" formmethod="post">Confirmar</button>
    </form>
{% endblock content %} 

gestion/templates/gestion/genre_form.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Ingreso de nuevo genero</h1>

        <form  role="form"  enctype="multipart/form-data" action="" method="POST" id="upload-image-form">   
            {% csrf_token %}   
            {{ form.as_p }}       
            
            <button type="submit" formmethod="post">Enviar</button>
        </form>
{% endblock content %} 

gestion/templates/gestion/language_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Listado de lenguajes</h1>
    <ul>
        {% for lenguage in object_list %}
        <li>
            {{ lenguage.name}}
        </li>
        {% endfor %}

        <br><a href="{% url 'add-language' %}">Agregar lenguaje</a>
    </ul>
{% endblock content %} 

gestion/templates/gestion/list_reserved_books_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Libros que tienes reservados</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li>
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No tienes libros reservados</p>
    {% endif %}       
{% endblock %}

gestion/templates/gestion/loan-book.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Prestamo del libro {{ bookinstance.book }}</h1>
    <form  role="form"  enctype="multipart/form-data" action="" method="POST" id="upload-image-form">   
        {% csrf_token %}

        {% if object.status == 'a' %}
            <h4>El libro está disponible, seleccione el prestatario</h4>   
                {{ form.borrower }}
            <button type="submit" formmethod="post">Prestar</button>
            <br><h5>Informe que la fecha de devolucion será el {{ object.due_back }}</h5>

        {% elif object.status == 'o' %}
            <h4>El usuario {{ object.borrower}} está devolviendo el libro?</h4>
            <button type="submit" formmethod="post">Devuelve</button>
    
        {% else %}
            <h4>El libro está reservado por {{ object.borrower }}</h4>
            <h4>Confirma que lo retira este usuario?</h4>
                {{ form.borrower }}
            <button type="submit" formmethod="post">Prestar</button>
            <br><h5>Informe que la fecha de devolucion será el {{ due_back }}</h5>
        {% endif %}
   
    </form>
{% endblock content %} 

gestion/templates/gestion/member_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Listado de miembros</h1>

    {% if object_list %}
    <ul>

      {% for member in object_list %}
      <li>
        <a href="{% url 'member-detail' member.id %}">{{ member.last_name }}, {{member.first_name}}</a>

    </li>
      {% endfor %}

      <br><a href="{% url 'add-member' %}">Agregar miembro</a>
    </ul>
    {% else %}
      <p>Todavia no hay miembros ingresados</p>
    {% endif %}       
{% endblock %}